FROM 555555555555.dkr.ecr.us-east-1.amazonaws.com/examplecom-golang1.2-nginx:ubuntu-16.04

ENV GOPATH=/go
ARG GOPATH=${GOPATH:-/go}

WORKDIR /go

COPY example/default/conf/supervisor-program.conf /etc/supervisor/conf.d/supervisor-program.conf
COPY example/default/conf/nginx.vhost.conf /etc/nginx/sites-available/default
COPY example/default/src/main.go ${GOPATH}/src/main.go